// Package paynp is a provider-neutral SDK for Nepali payment gateways.
//
// Every provider package (esewa, khalti, connectips, fonepay, imepay) returns a
// value implementing Provider, so a merchant integrates once and swaps providers.
package paynp

import (
	"context"
	"net/url"
	"time"
)

// Provider is the contract every payment gateway adapter implements.
//
// Flow: Initiate → send the user to Checkout → provider redirects back →
// ParseCallback → Lookup (server-to-server) → trust only Lookup's result.
type Provider interface {
	Name() ProviderName
	// Initiate prepares a payment. It may call the provider (Khalti) or only sign
	// a form (eSewa, ConnectIPS); either way nothing is charged yet.
	Initiate(ctx context.Context, req InitiateRequest) (*Checkout, error)
	// ParseCallback reads the provider's return redirect and checks its signature
	// when the provider signs it. Its Status is a hint, not proof of payment.
	// Unsigned callbacks never report SUCCESS, only PENDING or a failure hint.
	ParseCallback(query url.Values) (*Callback, error)
	// Lookup asks the provider for the authoritative status of a transaction.
	// A SUCCESS whose amount differs from req.Amount returns ErrAmountMismatch.
	Lookup(ctx context.Context, req LookupRequest) (*Transaction, error)
}

type ProviderName string

const (
	Esewa      ProviderName = "esewa"
	Khalti     ProviderName = "khalti"
	ConnectIPS ProviderName = "connectips"
	Fonepay    ProviderName = "fonepay"
	IMEPay     ProviderName = "imepay"
	HamroPay   ProviderName = "hamropay"
)

type Environment int

const (
	Sandbox Environment = iota
	Production
)

type Customer struct {
	Name  string
	Email string
	Phone string
}

type InitiateRequest struct {
	// TxnID is generated by the merchant and must be unique per attempt; it is
	// the key for Lookup. Keep it alphanumeric/hyphen and ≤ 20 chars to satisfy
	// every provider.
	TxnID       string
	Amount      Paisa
	Description string
	// SuccessURL and FailureURL receive the provider redirect. Khalti and Fonepay
	// use a single return URL (SuccessURL); ConnectIPS ignores both because its
	// URLs are registered with NCHL.
	SuccessURL string
	FailureURL string
	Customer   Customer
}

func (r InitiateRequest) Validate() error {
	switch {
	case r.TxnID == "":
		return invalid("TxnID is required")
	case r.Amount <= 0:
		return invalid("Amount must be positive")
	}
	return nil
}

// Checkout tells the caller how to hand the user to the provider.
type Checkout struct {
	Provider ProviderName
	// Method is http.MethodGet (redirect, Fields go in the query) or
	// http.MethodPost (auto-submitting form).
	Method string
	URL    string
	Fields map[string]string
	// ProviderRef is the provider's id for this payment when it issues one at
	// initiation (Khalti pidx, IME Pay token). Persist it; Lookup needs it.
	ProviderRef string
	ExpiresAt   time.Time
}

type Callback struct {
	TxnID       string
	ProviderRef string
	Status      Status
	Amount      Paisa
	Values      url.Values
}

type LookupRequest struct {
	TxnID string
	// Amount is the amount the merchant expects, from its own records — never
	// from the callback.
	Amount      Paisa
	ProviderRef string
	// Callback is required only by providers whose status API needs values the
	// provider returned on redirect (Fonepay, IME Pay); nil during reconciliation.
	Callback *Callback
}

type Transaction struct {
	Provider    ProviderName
	TxnID       string
	ProviderRef string
	Status      Status
	Amount      Paisa
	Raw         []byte
}

type Status string

const (
	StatusPending           Status = "PENDING"
	StatusSuccess           Status = "SUCCESS"
	StatusFailed            Status = "FAILED"
	StatusCanceled          Status = "CANCELED"
	StatusExpired           Status = "EXPIRED"
	StatusNotFound          Status = "NOT_FOUND"
	StatusRefunded          Status = "REFUNDED"
	StatusPartiallyRefunded Status = "PARTIALLY_REFUNDED"
)

// Final reports whether the status can no longer change through user action.
// NOT_FOUND is not final: the user may still be on the provider page.
func (s Status) Final() bool {
	switch s {
	case StatusSuccess, StatusFailed, StatusCanceled, StatusExpired, StatusRefunded, StatusPartiallyRefunded:
		return true
	}
	return false
}

// MatchAmount guards Lookup results: a successful transaction must carry the
// amount the merchant expected. On mismatch the transaction is withheld.
func MatchAmount(tx *Transaction, want Paisa) (*Transaction, error) {
	if tx.Status == StatusSuccess && tx.Amount != want {
		return nil, amountMismatch(want, tx.Amount)
	}
	return tx, nil
}
